### ISSUE TITLE
Issue with Terraform Destroy for ingressgateway

### ISSUE THREAD

**Issue by murphye** [murphye/cheap-gke-cluster#2]
```
Error: Error waiting for Deleting Network: The network resource 'projects/murphye/global/networks/my-network' is already being used by 'projects/murphye/zones/us-west4-a/networkEndpointGroups/ingressgateway'
```

**Comment by murphye** [comment]
Workaround: Delete the `ingressgateway` Network Endpoint Group from the Google Cloud Console under the Compute Engine section.

**Comment by murphye** [comment]
Updated docs with a workaround. `ingressgateway` NEG is not part of the Terraform inventory. Not sure what the best solution is.

**Comment by alexproca** [comment]
I created a PR with a suggestion for this issue. https://github.com/murphye/cheap-gke-cluster/pull/7

**Comment by murphye** [comment]
Still getting this error:

```
Error: Error waiting for Deleting Network: The network resource 'projects/murphye/global/networks/my-network' is already being used by 'projects/murphye/zones/us-west4-a/networkEndpointGroups/ingressgateway'
```

**Comment by murphye** [comment]
Fixed with depends_on

**Comment by alexproca** [comment]
👍

**Comment by devopslondon2021** [comment]
Hey, still having issue with the PR https://github.com/murphye/cheap-gke-cluster/pull/7 merge. 

@murphye  could you share a bit more details on how did you fix the issue? where did you add the depends_on?
